{"uuid": "3387559c-ccf8-4e48-bbac-32d8aa936d5f", "children": ["7f113f3d-2e40-4b49-a428-569d2d72483e"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=103.0.5060.134)\nStacktrace:\n#0 0x55e0c7fcccd3 <unknown>\n#1 0x55e0c7dd4968 <unknown>\n#2 0x55e0c7dce745 <unknown>\n#3 0x55e0c7dc1096 <unknown>\n#4 0x55e0c7dc2032 <unknown>\n#5 0x55e0c7dc1362 <unknown>\n#6 0x55e0c7dc0795 <unknown>\n#7 0x55e0c7dbf45f <unknown>\n#8 0x55e0c7dbf8c2 <unknown>\n#9 0x55e0c7dd63c2 <unknown>\n#10 0x55e0c7e3d60f <unknown>\n#11 0x55e0c7e29bb2 <unknown>\n#12 0x55e0c7e3cea8 <unknown>\n#13 0x55e0c7e29aa3 <unknown>\n#14 0x55e0c7dff3fa <unknown>\n#15 0x55e0c7e00555 <unknown>\n#16 0x55e0c80142bd <unknown>\n#17 0x55e0c8018418 <unknown>\n#18 0x55e0c7ffe36e <unknown>\n#19 0x55e0c8019078 <unknown>\n#20 0x55e0c7ff2bb0 <unknown>\n#21 0x55e0c8035d58 <unknown>\n#22 0x55e0c8035ed8 <unknown>\n#23 0x55e0c804fcfd <unknown>\n#24 0x7fb8306e26db <unknown>\n\n", "trace": "  File \"/home/dir-oazis/python/otus/lesson_7_new/lesson_6/env/lib/python3.7/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/dir-oazis/python/otus/lesson_7_new/lesson_6/env/lib/python3.7/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/dir-oazis/python/otus/lesson_7_new/lesson_6/env/lib/python3.7/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/dir-oazis/python/otus/lesson_7_new/lesson_6/conftest.py\", line 46, in browser\n    driver.get(url)\n  File \"/home/dir-oazis/python/otus/lesson_7_new/lesson_6/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 442, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/home/dir-oazis/python/otus/lesson_7_new/lesson_6/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"/home/dir-oazis/python/otus/lesson_7_new/lesson_6/env/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1659857015540, "stop": 1659857018900}], "afters": [{"name": "browser::close", "status": "passed", "start": 1659857019320, "stop": 1659857019399}], "start": 1659857015540, "stop": 1659857019399}