{"uuid": "24637461-5362-4e54-96db-cc1f6827d59d", "children": ["efa14298-3ed1-432c-8ea7-a02fb529a856"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=103.0.5060.134)\nStacktrace:\n#0 0x565319291cd3 <unknown>\n#1 0x565319099968 <unknown>\n#2 0x565319093745 <unknown>\n#3 0x565319086096 <unknown>\n#4 0x565319087032 <unknown>\n#5 0x565319086362 <unknown>\n#6 0x565319085795 <unknown>\n#7 0x56531908445f <unknown>\n#8 0x5653190848c2 <unknown>\n#9 0x56531909b3c2 <unknown>\n#10 0x56531910260f <unknown>\n#11 0x5653190eebb2 <unknown>\n#12 0x565319101ea8 <unknown>\n#13 0x5653190eeaa3 <unknown>\n#14 0x5653190c43fa <unknown>\n#15 0x5653190c5555 <unknown>\n#16 0x5653192d92bd <unknown>\n#17 0x5653192dd418 <unknown>\n#18 0x5653192c336e <unknown>\n#19 0x5653192de078 <unknown>\n#20 0x5653192b7bb0 <unknown>\n#21 0x5653192fad58 <unknown>\n#22 0x5653192faed8 <unknown>\n#23 0x565319314cfd <unknown>\n#24 0x7fc9454896db <unknown>\n\n", "trace": "  File \"/home/dir-oazis/python/otus/lesson_7_new/lesson_6/env/lib/python3.7/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/dir-oazis/python/otus/lesson_7_new/lesson_6/env/lib/python3.7/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/dir-oazis/python/otus/lesson_7_new/lesson_6/env/lib/python3.7/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/dir-oazis/python/otus/lesson_7_new/lesson_6/conftest.py\", line 46, in browser\n    driver.get(url)\n  File \"/home/dir-oazis/python/otus/lesson_7_new/lesson_6/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 442, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/home/dir-oazis/python/otus/lesson_7_new/lesson_6/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"/home/dir-oazis/python/otus/lesson_7_new/lesson_6/env/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1659857019406, "stop": 1659857021863}], "afters": [{"name": "browser::close", "status": "passed", "start": 1659857021956, "stop": 1659857022034}], "start": 1659857019406, "stop": 1659857022034}